dist: trusty
language: java
jdk:
  - openjdk7
  - openjdk8

script:
   - mvn test

matrix:
  include:
    - jdk: openjdk8
      after_success:
        - mvn checkstyle:checkstyle
        - mvn clean cobertura:cobertura coveralls:report
